### ISSUE TITLE
Product Listing Page: View More buttons are not align

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#14]
Ipad Portrait:
![image](https://cloud.githubusercontent.com/assets/13363508/9194307/d73819ae-404c-11e5-813f-37a9a688dcbe.png)

Ipad landscape:
![image](https://cloud.githubusercontent.com/assets/13363508/9194321/ec0fbcc4-404c-11e5-95d3-836f27d54d5a.png)

**Comment by ramoncebudigital** [comment]
same issue  https://github.com/titan-cebu/Mandurah-Boat-Bike-Hire/issues/13

**Comment by maehtitan** [comment]
This issue is meant for mobile. It looks like this in
