### ISSUE TITLE
Admin - Business Details: Removing the Sunday & Public Holidays data info field will not remove in the front-end contact us page Sat-Sun label and field

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#2]
![image](https://cloud.githubusercontent.com/assets/13363508/8977019/7b872e9e-36c7-11e5-8f23-8deb16727c0d.png)

**Comment by ramoncebudigital** [comment]
added new label in the back-end "Saturday & Sunday"
