### ISSUE TITLE
Homepage: Apply fade effect in the featured image since the edge is visible

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#22]
![image](https://cloud.githubusercontent.com/assets/13363508/8999911/16c400de-3773-11e5-948a-dc0630c93e0d.png)

**Comment by maehtitan** [comment]
Fixed in all browsers except for Chrome & IE 11, please check it below

IE11
![image](https://cloud.githubusercontent.com/assets/13363508/9192764/6ce1505e-4040-11e5-9dcd-c068fe66554f.png)

Chrome
![image](https://cloud.githubusercontent.com/assets/13363508/9192831/150ed21a-4041-11e5-9b39-55c3f9a03e2f.png)

**Comment by ramoncebudigital** [comment]
it's all working on my side, maybe you didn't refresh hard the browser.
IE
![screenshot_4](https://cloud.githubusercontent.com/assets/11186436/9216252/a0eb9d2a-40e8-11e5-9af8-065f0ccfa367.png)

CHROME
![screenshot_5](https://cloud.githubusercontent.com/assets/11186436/9216267/c0f4939c-40e8-11e5-90ea-cbf57637742a.png)
