### ISSUE TITLE
Homepage - Banner: banner transition should only rotates every after 5 seconds

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#26]

**Comment by ramoncebudigital** [comment]
I think the banner was rotating every 5 seconds, maybe because you didn't see the banner images some of them are the same image, that's why you didn't see it rotating every 5 seconds.

**Comment by maehtitan** [comment]
I already changed the banner images alternately but there are really instances that the banner rotates for more than 5 seconds, I got my watch here with me counting in actual seconds :)

Curious on the code of the script so I found out that you're not using the slicknav as per project scope mentioned instead you used this http://mandurah.stage.titanweb.com.au/wp-content/themes/titan/js/main-slider.js?ver=4.2.2

**Comment by ramoncebudigital** [comment]
I displayed only 2 items, now check the duration time.
