### ISSUE TITLE
Homepage: Redirected to the wrong pages

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#27]
![image](https://cloud.githubusercontent.com/assets/13363508/9001155/01273724-3786-11e5-85bd-290593bc7e54.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

For this bug, the pages have been redirected, just a notice, we have activated a plugin, in which we can reorder a post type, and for the featured lead ins, the first 2 order will be displayed on the homepage as featured lead-ins, hope this makes sense.

Cheers,
Christian
