### ISSUE TITLE
Contact Us: The font color is not the same on the rest of the browsers

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#32]
Browser: IE9

![image](https://cloud.githubusercontent.com/assets/13363508/9001568/b6d61504-378b-11e5-8a35-87341f777e6d.png)

**Comment by ramoncebudigital** [comment]
unfortunately IE css style for placeholder won't work on IE9
see link below
https://msdn.microsoft.com/en-us/library/hh772745(v=vs.85).aspx

**Comment by maehtitan** [comment]
Placeholder works in IE9 on the link below:
http://bridalbentleysperth.stage.titanweb.com.au/booking-form/

**Comment by ramoncebudigital** [comment]
yeah, but that's not Placeholder attribute, the form uses the label as the placeholder.
