### ISSUE TITLE
Boat Hire - Mobile: Please center-align the bottom menus

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#56]
Device: Ipad

![image](https://cloud.githubusercontent.com/assets/13363508/9030307/7e455f48-39d3-11e5-8c22-93ce4b797025.png)

**Comment by ramoncebudigital** [comment]
an enhancement perhaps not a bug

**Comment by maehtitan** [comment]
But in Itouch 5 and S4 it is center-align in landscape view so make it consistent in Ipad portrait view
