### ISSUE TITLE
Boat Hire - Single View: Incorrect redirection to the Hire Now button

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#59]

**Comment by maehtitan** [comment]
Still redirected to About Us page instead of Contact US as per project scope mentioned

**Comment by ramoncebudigital** [comment]
working on my side.
see screenshot
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/9191279/dfe67b88-4031-11e5-8301-f1f89917da6c.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

Default redirection on hire now is now on contact us, you can set the default link by going to global fields options.

Thanks,
Christian
