### ISSUE TITLE
Gallery: Please style properly the extended album, at the moment it creates a big space right next to the album

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#6]
![image](https://cloud.githubusercontent.com/assets/13363508/8978348/f67bf7fe-36d3-11e5-8e84-2a63075f4d59.png)

**Comment by christiancebudigital** [comment]
Hi Maeh,

This is invalid, as this is for the layout for extenden album.

Thanks,
Christian

**Comment by maehtitan** [comment]
It's not invalid since it is mentioned in the knowledgebase link here: https://knowledgebase.titanweb.com.au/implementation-practices/nggallery-implementation-practices/gallery-layout-and-styles to follow the Gallery page design if there's no design for the albums

**Comment by christiancebudigital** [comment]
Hi Mae,

The reason we flagged this as invalid, it is because, the layout and purpose of extended album is to indicated description of the album, see link of ngg extended for its purpose [ http://www.nextgen-gallery.com/extend-album-settings/ ], please confirm with bernard also.

Cheers,
Christian

**Comment by maehtitan** [comment]
Actually, it is be possible to implement that the extended album will be dynamically extends the border IF there are text/description added and it won't extend if no text found but Yes you're right I found out that the NGG galley link you have given is not dynamic, thanks :)
