### ISSUE TITLE
Admin - Pages: Please remove unnecessary pages

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#64]
As per copy provided no Hire Now page mentioned

![image](https://cloud.githubusercontent.com/assets/13363508/9105456/89f05f5e-3c4a-11e5-8ab1-e676d7cfcf95.png)

**Comment by ramoncebudigital** [comment]
Hire now page is use for product single button "hire now" for landing page.

**Comment by maehtitan** [comment]
But in project scope mentioned it should be redirected to Contact Us page
