### ISSUE TITLE
Boat Hire - Single View: The Hire Now button is redirected to the contact page link URL so, how will I know that this products I was clicking was came from that particular product?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#66]
Will comment this part after the contact form is fix.

**Comment by christiancebudigital** [comment]
Hi Maeh,

We get your point, but base on the project scope, it will redirect to contact us now page, although we've already asked this one out to Jolene, she said that it will redirect to contact us only, green text on project scope means their feedback on the site, lets make it simple first, before we proceed to implementation that the client want :D.

Thanks,
Christian
