### ISSUE TITLE
Bicycle Hire: The featured image missing prev and next button and not link to the thumbnail images

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Mandurah-Boat-Bike-Hire#7]
Apply fixes also in Boat-Hire Single View page

![image](https://cloud.githubusercontent.com/assets/13363508/8978750/a004e896-36d7-11e5-8999-9422c0b7fa9d.png)

**Comment by maehtitan** [comment]
Still missing prev and next button and also still now link to thumbnail images

**Comment by maehtitan** [comment]
Hi Ramon,

Prev and next button already fixed but can you please make the whole featured image as clickable not just the magnifying lens icon only

Also the functionality of the featured image linking to the gallery thumbnails has an error, I've tried clicking the image without gallery thumbnails and the previous and next button is working which is supposed to be disabled since there is only 1 image obviously.

An When I tried checking a featured image with gallery thumbnails, it navigates more than 3 times

Example below:

![image](https://cloud.githubusercontent.com/assets/13363508/9192659/96a0f2f6-403f-11e5-907f-dd673d2cc0cf.png)

**Comment by ramoncebudigital** [comment]
If I will make the whole image clickable the magnify icon will be useless.

**Comment by maehtitan** [comment]
The magnifying icon supposedly indicates that this particular images is clickable and can be viewed/zoomed in bigger image not the other way around.

**Comment by maehtitan** [comment]
The featured still now clickable at the moment
